import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: Platform.OS === 'web' ? '100vh' : '100%',
  },
  container: {
    flex: 1,
    width: '100%',
  },
  lightContainer: {
    backgroundColor: '#87CEEB', // Celeste claro
  },
  darkContainer: {
    backgroundColor: '#87CEEB', // Azul oscuro
  },
  bubblesContainer: {
    pointerEvents: 'none',
    zIndex: 0,
  },
  mainBox: {
    width: Platform.OS === 'web' ? '40%' : '90%',
    minWidth: Platform.OS === 'web' ? 400 : '90%',
    maxWidth: 500,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    zIndex: 1,
  },
  headerImage: {
    width: '100%',
    height: 180,
    marginBottom: 10,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FF6B6B',
    marginLeft: 10,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  form: {
    width: '100%',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    position: 'relative',
  },
  icon: {
    position: 'absolute',
    left: 15,
    zIndex: 1,
  },
  input: {
    flex: 1,
    paddingLeft: 50,
    paddingRight: 15,
    paddingVertical: 12,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#FFD166',
    fontSize: 16,
    color: '#333',
    backgroundColor: '#FFF9F2',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 15,
    marginTop: 20,
    backgroundColor: '#FF9F1C',
    shadowColor: '#FF9F1C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonIcon: {
    marginLeft: 10,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  switchText: {
    fontSize: 16,
    color: '#666',
  },
  switchLink: {
    fontSize: 16,
    color: '#06AED5',
    fontWeight: 'bold',
    marginLeft: 5,
    textDecorationLine: Platform.OS === 'web' ? 'underline' : 'none',
  },

   pickerContainer: {
    flex: 1,
    paddingLeft: 50,
    paddingRight: 15,
    paddingVertical: 12,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#FFD166',
    fontSize: 16,
    color: '#333',
    backgroundColor: '#FFF9F2',
    marginBottom: 16,
  },
  picker: {
    flex: 1,
    color: "#000",
    fontSize: 16,
    height: 50,
  },
});